In [6]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#LabelEncoder() 내 transform 메서드를 이용해서 인코딩함
print('인코딩 변환값,',labels)
#LabelEncoder() 내 classes_는 학습의 feature값들을 반환 
print('인코딩 클래스:', encoder.classes_)
#반대로 inverse_transform은 리스트형식의 인코딩 값을 디코딩해주는 메서드
print('디코딩 원본 값:',encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

인코딩 변환값, [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
디코딩 원본 값: ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [8]:
encoder.fit_transform(items)

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [50]:
import pandas as pd

titanic = pd.read_csv('./csv/train.csv')
titanic = titanic.drop(['PassengerId','Pclass','Name','SibSp','Parch','Ticket','Fare','Cabin'], axis=1)
titanic.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   Embarked  889 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [58]:
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())
titanic['Embarked'] = titanic['Embarked'].fillna('S')


In [54]:
encoder = LabelEncoder()

Sex = list(titanic['Sex'])
Sex_ = encoder.fit_transform(Sex)
Embarked = list(titanic['Embarked'])
Embarked_ = encoder.fit_transform(Embarked)

titanic['Sex'] = Sex_
titanic['Embarked'] = Embarked_

titanic

Survived  Sex        Age  Embarked
0           0    0  22.000000         2
1           1    0  38.000000         0
2           1    0  26.000000         2
3           1    0  35.000000         2
4           0    0  35.000000         2
..        ...  ...        ...       ...
886         0    0  27.000000         2
887         1    0  19.000000         2
888         0    0  29.699118         2
889         1    0  26.000000         0
890         0    0  32.000000         1

[891 rows x 4 columns]

In [57]:
titanic['Sex'] = encoder.fit_transform(titanic['Sex'])
titanic['Embarked'] = encoder.fit_transform(titanic['Embarked'])
titanic

Survived  Sex        Age  Embarked
0           0    0  22.000000         2
1           1    0  38.000000         0
2           1    0  26.000000         2
3           1    0  35.000000         2
4           0    0  35.000000         2
..        ...  ...        ...       ...
886         0    0  27.000000         2
887         1    0  19.000000         2
888         0    0  29.699118         2
889         1    0  26.000000         0
890         0    0  32.000000         1

[891 rows x 4 columns]

## 원-핫 인코딩 해보기

In [62]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
items =  ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
    
#숫자값 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items) 
#1차원 리스트로 된 어레이를 2차원 데이터로 변환 (-1을 쓰면 행or열에 쓴 숫자 값에 따라서 알아서 맞춰줌)
# reshape(-1,1)은 전치행렬값으로 출력 (행과 열의 수가 바뀜)
labels = labels.reshape(-1,1)

#원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels) #2차원 어레이를 다시 인코딩
print('원-핫 인코딩 데이터')
print(oh_labels.toarray()) #
print('원-핫 인코딩 데이터 차원')
print(oh_labels.reshape)



원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
<bound method spmatrix.reshape of <8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>>


In [68]:
df = pd.read_csv('./csv/train.csv')
one_encoder = OneHotEncoder()
trans_data = one_encoder.fit_transform(df['Sex']) #어레이로 나옴
trans_data.toarray()

ValueError: Expected 2D array, got 1D array instead:
array=['male' 'female' 'female' 'female' 'male' 'male' 'male' 'male' 'female'
 'female' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'male'
 'female' 'female' 'male' 'male' 'female' 'male' 'female' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'male' 'female' 'female' 'female' 'female' 'male' 'female'
 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'female'
 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'female'
 'male' 'male' 'male' 'male' 'female' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male'
 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'male' 'female'
 'male' 'male' 'male' 'female' 'female' 'female' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'female'
 'male' 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'male'
 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'female'
 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'female' 'male'
 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'female'
 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'male'
 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'female'
 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'male' 'male' 'male' 'male' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'female' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'female'
 'female' 'female' 'male' 'male' 'female' 'female' 'male' 'female'
 'female' 'male' 'male' 'female' 'female' 'male' 'female' 'male' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'female'
 'female' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'female' 'female' 'male' 'male' 'male' 'male'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'female' 'male' 'male' 'female' 'male'
 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'female'
 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'female'
 'male' 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'female'
 'female' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female'
 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'male'
 'female' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'male' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'female' 'male'
 'male' 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'female'
 'male' 'male' 'female' 'female' 'female' 'male' 'female' 'male' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'male' 'male'
 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'female' 'male'
 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'female' 'male' 'male'
 'female' 'female' 'female' 'male' 'female' 'female' 'male' 'male' 'male'
 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'female'
 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'male'
 'male' 'male' 'male' 'male' 'female' 'female' 'female' 'male' 'female'
 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'male'
 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'female'
 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'female' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'female'
 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male' 'male'
 'female' 'male' 'male' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'male'
 'male' 'male' 'female' 'female' 'male' 'female' 'female' 'male' 'male'
 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female'
 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'female' 'male' 'male' 'male' 'male'
 'female' 'male' 'female' 'male' 'male' 'female' 'male' 'female' 'female'
 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'male' 'male' 'male' 'male' 'male' 'female' 'male'
 'female' 'male' 'male' 'male' 'female' 'male' 'male' 'female' 'male'
 'male' 'male' 'female' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'male'
 'male' 'male' 'male' 'male' 'male' 'female' 'male' 'male' 'male' 'male'
 'male' 'male' 'female' 'male' 'male' 'female' 'female' 'female' 'female'
 'female' 'male' 'female' 'male' 'male' 'male' 'female' 'female' 'male'
 'female' 'female' 'male' 'male' 'male' 'male' 'female' 'male' 'male'
 'female' 'female' 'male' 'male' 'male' 'female' 'female' 'male' 'female'
 'male' 'male' 'female' 'male' 'female' 'female' 'male' 'male'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [63]:
encoder.transform(items)

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 판다스에서 지원하는 원-핫 인코딩 APi get_dummies()
df = pd.DataFrame({'item': ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

In [71]:
import pandas as pd
df = pd.read_csv('./csv/train.csv')
df.drop(['PassengerId','Pclass','Name','SibSp','Parch','Ticket','Fare','Cabin'], axis=1 , inplace=True)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna('S')


In [74]:
data = df.loc[:,'Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [76]:
dummy_embark = pd.get_dummies(data)

In [79]:
dummy_data = pd.get_dummies(df[['Sex','Embarked']])

In [81]:
dummy_data

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [87]:
dummy_df = pd.concat([df,dummy_data], axis = 1)

In [91]:
dummy_df.drop(['Sex','Embarked'],axis=1,inplace=True)

KeyError: "['Sex', 'Embarked'] not found in axis"

In [92]:
dummy_df['Age'].

Survived        Age  Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0  22.000000           0         1           0           0           1
1           1  38.000000           1         0           1           0           0
2           1  26.000000           1         0           0           0           1
3           1  35.000000           1         0           0           0           1
4           0  35.000000           0         1           0           0           1
..        ...        ...         ...       ...         ...         ...         ...
886         0  27.000000           0         1           0           0           1
887         1  19.000000           1         0           0           0           1
888         0  29.699118           1         0           0           0           1
889         1  26.000000           0         1           1           0           0
890         0  32.000000           0         1           0           1           0

[891 rows x 7 columns]